# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: os
description: Basic Fedora Sway installation with required packages for supporting NOVA Kiosk and NOVA Keys.

base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /
      - source: etc/greetd/config.toml
        destination: /etc/greetd/config.toml

  - type: dnf
    install:
      packages:
        - sway
        - swayidle
        - chromium
        - gtk4
        - gtk4-layer-shell
        - anthy-unicode
        - libhangul
        - librime
        - brise
        - google-noto-sans-cjk-fonts
        - cups
        - cups-client
        - cups-filters
        - NetworkManager-tui
        - ethtool
        - sudo
        - wayvnc
        - openssh-server
        - greetd
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: script
    scripts:
      - install-agent.sh
      - install-novakeys.sh

  - type: systemd
    system:
      enabled:
        - NetworkManager.service
        - sshd.service
        - greetd.service
        - cups.service
        - novakiosk-kiosk-lp-membership.service
        - novakiosk-enable-linger.service
        - novakiosk-wol.service

    user:
      enabled:
        - novakiosk-agent.service

  - type: signing
